[project]
name = "ai-memory-illusion"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "leonardo-moraes360", email = "leogm360.work@proton.me" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
ai-memory-illusion = "ai_memory_illusion:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
